config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "tasks", to: "tasks#index"
  get "tasks", to: "tasks#list"
  get "tasks/new", to: "tasks#new", as: :new_task
  post "tasks", to: "tasks#create"
  get "tasks/:id", to: "tasks#show", as: :task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@tasks)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path(@tasks)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">

    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed? %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form", task: @task %>

<p> <%=link_to "Home", tasks_path(@edit) %> </p>

app/views/tasks/index.html.erb
<ul>
  <% @tasks.each do |task| %>
    <li>
    <% if task.completed? %>
    <i class="fa-solid fa-square-check"></i>
    <%= link_to task.title, task_path(task) %> <%= link_to "Delete", task_path(task),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
  <% else %>
    <i class="fa-regular fa-circle-xmark"></i>
    <%= link_to task.title, task_path(task) %> <%= link_to "Delete", task_path(task),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
  <% end %>
  </li>
  <%end%>
</ul>
<h1> <%= link_to "Create new task", new_task_path(@task) %> </h1>

app/views/tasks/new.html.erb
<%= render "form", task: @task %>

<p> <%=link_to "Home", tasks_path(@task) %> </p>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p> Completed? <% if @task.completed?  %>
    <i class="fa-solid fa-square-check"></i>
  <% else %>
    <i class="fa-regular fa-circle-xmark"></i>
  <% end %>
</p>

<p> <%=link_to "Edit this task", edit_path(@task) %></p>

<p> <%=link_to "Home", tasks_path(@task) %> </p>